# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b212b4dbc42eacad57cdfc1521461fdd9c92d415a5e5c6d8e22da8d3aa427a22318546d5f764ebf7c3c42a0df01643f29589de391a1379c4e36138edf5ac87f9

test:
  secret_key_base: 7a8b890e2fe28e6e156a5893a00605236d234908f5aa4a7ca187c2693ffed4cf97a200b735b40dc6909d31b122c3d17894119fb8b3f2a48d026fdef990fccf60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
